url: "http://www.markitt.com.br/"
baseurl: "/finalfinal"

# Site settings
title: Markitt
email: contato@markitt.com.br
description: "Atuamos no rastreamento e logística interna de armazéns de café, mapeando o trajeto dos grãos com o auxílio da visão computacional."


# Team names, titles and social links


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Belo Horizonte - MG
  - line: Brasil

# Build settings
markdown: kramdown
permalink: /:title